# Generated by Django 2.1.2 on 2018-10-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20181026_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='song_title',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='music',
            name='song_url',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
