# Generated by Django 2.1.2 on 2018-10-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20181026_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Rock', 'Rock'), ('Metal', 'Metal'), ('Alternative', 'Alternative'), ('Latin', 'Latin'), ('Disco', 'Disco'), ('Pop', 'Pop'), ('Blues', 'Blues')], default=None, max_length=50),
        ),
    ]
