# Generated by Django 2.1.2 on 2018-10-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20181028_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('Jazz', 'jazz'), ('Classical', 'Classical'), ('Reggae', 'reggae'), ('Rock', 'rock'), ('Metal', 'metal'), ('Alternative', 'alternative'), ('Latin', 'latin'), ('Disco', 'disco'), ('Pop', 'pop'), ('Blues', 'blues')], default=None, max_length=50),
        ),
    ]
